#include "gatt_client.h"
#include "gatt_service_discovery.h"
#include "gatt_service_discovery_private.h"

/* List of gatt client identifiers (generated by the gatt client create macros in gatt_client.h) */
extern const client_id_t gatt_ams_client_id;
extern const client_id_t gatt_ancs_client_id;

bool GattServiceDiscovery_Init(Task init_task)
{
    UNUSED(init_task);
    static const client_id_t* client_priority_discover[] =
    {
        &gatt_ams_client_id,
        &gatt_ancs_client_id,
    };

    GattClientInit(client_priority_discover);
    gattServiceDiscovery_Init(client_priority_discover, sizeof(client_priority_discover)/sizeof(client_priority_discover[0]));
    return TRUE;
}
