/* Copyright (c) 2017 Qualcomm Technologies International, Ltd. */
/*   %%version */
/**
 * \file
 * Implementations of non-autogenerated audio-related trap calls
 */
#include "trap_api/trap_api_private.h"
#include "ipc/ipc.h"

#if TRAPSET_WAKE_ON_AUDIO
bool AudioDspGetClock(audio_dsp_clock *dsp_clock)
{
    IPC_AUDIO_DSP_GET_CLOCK send_prim;
    IPC_AUDIO_DSP_GET_CLOCK_RSP resp_prim;
    send_prim.header.id = IPC_SIGNAL_ID_AUDIO_DSP_GET_CLOCK;
    ipc_transaction(IPC_SIGNAL_ID_AUDIO_DSP_GET_CLOCK, &send_prim, sizeof(send_prim),
                    IPC_SIGNAL_ID_AUDIO_DSP_GET_CLOCK_RSP, &resp_prim);

    if (dsp_clock && resp_prim.ret)
    {
        *dsp_clock = resp_prim.dsp_clock;
    }
    return resp_prim.ret;
}
#endif /* TRAPSET_WAKE_ON_AUDIO */
