/* Copyright (c) 2019 Qualcomm Technologies International, Ltd. */
/*   %%version */
/**
 * \file
 * Implementations of non-autogenerated radio transmit trap calls
 */

#include "trap_api/trap_api_private.h"

#if TRAPSET_TEST2

bool Test2TxData(HopChannels * channel, uint16 power, uint16 hopping,
                 uint16 payload, uint16 packet_type, uint16 packet_length,
                 const bdaddr * bt_addr, uint16 lt_addr)
{
    IPC_TEST2_TX_DATA ipc_send_prim;
    IPC_BOOL_RSP ipc_recv_prim;

    BD_ADDR_T bd_addr;
    bd_addr.uap = bt_addr->uap;
    bd_addr.lap = bt_addr->lap;
    bd_addr.nap = bt_addr->nap;

    ipc_send_prim.channel = channel;
    ipc_send_prim.power = power;
    ipc_send_prim.hopping = hopping;
    ipc_send_prim.payload = payload;
    ipc_send_prim.packet_type = packet_type;
    ipc_send_prim.packet_length = packet_length;
    ipc_send_prim.bt_addr = &bd_addr;
    ipc_send_prim.lt_addr = lt_addr;

    ipc_transaction(IPC_SIGNAL_ID_TEST2_TX_DATA, &ipc_send_prim, sizeof(ipc_send_prim),
                    IPC_SIGNAL_ID_TEST2_TX_DATA_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

bool Test2RxStart(HopChannels * channel, uint16 hopping, uint16 payload,
                  uint16 packet_type, uint16 packet_length,
                  const bdaddr * bt_addr, uint16 lt_addr)
{
    IPC_TEST2_RX_START ipc_send_prim;
    IPC_BOOL_RSP ipc_recv_prim;

    BD_ADDR_T bd_addr;
    bd_addr.uap = bt_addr->uap;
    bd_addr.lap = bt_addr->lap;
    bd_addr.nap = bt_addr->nap;

    ipc_send_prim.channel = channel;
    ipc_send_prim.hopping = hopping;
    ipc_send_prim.payload = payload;
    ipc_send_prim.packet_type = packet_type;
    ipc_send_prim.packet_length = packet_length;
    ipc_send_prim.bt_addr = &bd_addr;
    ipc_send_prim.lt_addr = lt_addr;

    ipc_transaction(IPC_SIGNAL_ID_TEST2_RX_START, &ipc_send_prim, sizeof(ipc_send_prim),
                    IPC_SIGNAL_ID_TEST2_RX_START_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

#endif /* TRAPSET_TEST2 */
