/**************************************************************************/
/* Copyright (c) 2020 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           10276

#define ENTRY_POINT_TTP_CONFIGURE_SP_ADJUSTMENT  0x04001d5f /* $_ttp_configure_sp_adjustment */
#define ENTRY_POINT_TTP_ADJUST_TTP_TIMESTAMP     0x04001d85 /* $_ttp_adjust_ttp_timestamp */
#define ENTRY_POINT_TTP_GET_MSG_STATE_PARAMS     0x04001dad /* $_ttp_get_msg_state_params */
#define ENTRY_POINT_TTP_CONFIGURE_STATE_PARAMS   0x04001dfd /* $_ttp_configure_state_params */
#define ENTRY_POINT_TTP_GET_STATE_PARAMS_STATUS  0x04001ea9 /* $_ttp_get_state_params_status */
#define ENTRY_POINT_GET_MSG_SP_ADJUSTMENT        0x04001d43 /* $_ttp_get_msg_sp_adjustment */
#define ENTRY_POINT_TTP_GET_MSG_ADJUST_TTP_TIMESTAMP 0x04001d51 /* $_ttp_get_msg_adjust_ttp_timestamp */
#define ENTRY_POINT_THREAD_OFFLOAD_UPDATE_P1_MEM_LOCATION 0x0400215f /* $_thread_offload_update_p1_mem_location */
#define ENTRY_POINT_STREAM_SHORT_DOWNSTREAM_PROBE 0x04003127 /* $_stream_short_downstream_probe */
#define ENTRY_POINT_STREAM_CALC_DOWNSTREAM_AMOUNT_WORDS 0x04003199 /* $_stream_calc_downstream_amount_words */
#define ENTRY_POINT_STREAM_TRANSFORM_FROM_BUFFER 0x040031bf /* $_stream_transform_from_buffer */

#endif /* SUBSYS3_PATCH0_FW00001BD0_MAP_PUBLIC_H */
