/*!
\copyright  Copyright (c) 2019-2020 Qualcomm Technologies International, Ltd.
            All Rights Reserved.
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\file
\brief      Kymera module to handle the messages generated by Voice Assistant related public APIs

*/

#include "kymera.h"
#include "kymera_va.h"
#include "kymera_va_common.h"
#include <logging.h>

typedef enum
{
    KYMERA_INTERNAL_VOICE_CAPTURE_START,
    KYMERA_INTERNAL_VOICE_CAPTURE_STOP,
    KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_START,
    KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_STOP,
    KYMERA_INTERNAL_WAKE_UP_WORD_RESPONSE
} internal_message_ids;

typedef struct
{
    KymeraVoiceCaptureStarted callback;
    va_audio_voice_capture_params_t params;
} KYMERA_INTERNAL_VOICE_CAPTURE_START_T;

typedef struct
{
    KymeraWakeUpWordDetected callback;
    va_audio_wuw_detection_params_t params;
} KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_START_T;

typedef struct
{
    kymera_wuw_detected_response_t response;
} KYMERA_INTERNAL_WAKE_UP_WORD_RESPONSE_T;

typedef struct
{
    uint16 detection_confidence;
    uint16 start_ts_msb;
    uint16 start_ts_lsb;
    uint16 end_ts_msb;
    uint16 end_ts_lsb;
} graph_manager_wuw_detection_info_t;

typedef struct
{
    uint16 number_of_channels;
    graph_manager_wuw_detection_info_t channel[1];
} graph_manager_wuw_detection_message_t;

static void kymera_VaMessageHandler(Task task, MessageId id, Message msg);
static void kymera_WakeUpWordDetectionHandler(Task task, MessageId id, Message msg);
static const TaskData msg_handler = { kymera_VaMessageHandler };
static const TaskData wuw_detection_handler = { kymera_WakeUpWordDetectionHandler };

static KymeraWakeUpWordDetected wuw_detected_callback = NULL;

static void kymera_VaMessageHandler(Task task, MessageId id, Message msg)
{
    UNUSED(task);
    switch (id)
    {
        case KYMERA_INTERNAL_VOICE_CAPTURE_START:
        {
            const KYMERA_INTERNAL_VOICE_CAPTURE_START_T *req = msg;
            req->callback(Kymera_StartVaLiveCapture(&req->params));
        }
        break;

        case KYMERA_INTERNAL_VOICE_CAPTURE_STOP:
            Kymera_StopVaCapture();
        break;

        case KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_START:
        {
            const KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_START_T *req = msg;
            Kymera_StartVaWuwDetection((Task) &wuw_detection_handler, &req->params);
            wuw_detected_callback = req->callback;
        }
        break;

        case KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_STOP:
            Kymera_StopVaWuwDetection();
            wuw_detected_callback = NULL;
        break;

        case KYMERA_INTERNAL_WAKE_UP_WORD_RESPONSE:
        {
            const KYMERA_INTERNAL_WAKE_UP_WORD_RESPONSE_T *req = msg;

            if (req->response.start_capture)
            {
                PanicFalse(req->response.capture_callback != NULL);
                req->response.capture_callback(Kymera_StartVaWuwCapture(&req->response.capture_params));
            }
            else
            {
                Kymera_IgnoreDetectedVaWuw();
            }
        }
        break;
    }
}

static va_audio_wuw_detection_info_t kymera_GetWuwDetectionInfo(const MessageFromOperator *op_msg)
{
    va_audio_wuw_detection_info_t info = {0};
    const graph_manager_wuw_detection_message_t *message = (const graph_manager_wuw_detection_message_t *) &op_msg->message[3];

    PanicFalse(message->number_of_channels == 1);
    info.detection_confidence = message->channel[0].detection_confidence;
    info.start_timestamp = UINT32_BUILD(message->channel[0].start_ts_msb, message->channel[0].start_ts_lsb);
    info.end_timestamp   = UINT32_BUILD(message->channel[0].end_ts_msb, message->channel[0].end_ts_lsb);

    return info;
}

static void kymera_WakeUpWordDetectionHandler(Task task, MessageId id, Message msg)
{
    UNUSED(task);
    UNUSED(id);

    Kymera_VaWuwDetected();

    if (MessagesPendingForTask((Task) &msg_handler, NULL))
    {
        DEBUG_LOG("kymera_WakeUpWordDetectionHandler: Ignore WuW detected due to other pending client requests");
        Kymera_IgnoreDetectedVaWuw();
    }
    else
    {
        DEBUG_LOG("kymera_WakeUpWordDetectionHandler: Get client response");
        MESSAGE_MAKE(message, KYMERA_INTERNAL_WAKE_UP_WORD_RESPONSE_T);
        va_audio_wuw_detection_info_t wuw_info = kymera_GetWuwDetectionInfo(msg);
        kymeraTaskData *theKymera = KymeraGetTaskData();
        PanicFalse(wuw_detected_callback != NULL);
        message->response = wuw_detected_callback(&wuw_info);
        MessageSendConditionally((Task) &msg_handler, KYMERA_INTERNAL_WAKE_UP_WORD_RESPONSE, message, &theKymera->lock);
    }
}

void Kymera_StartVoiceCapture(KymeraVoiceCaptureStarted callback, const va_audio_voice_capture_params_t *params)
{
    MESSAGE_MAKE(message, KYMERA_INTERNAL_VOICE_CAPTURE_START_T);
    kymeraTaskData *theKymera = KymeraGetTaskData();
    PanicFalse(callback && params);
    message->callback = callback;
    message->params = *params;
    MessageSendConditionally((Task) &msg_handler, KYMERA_INTERNAL_VOICE_CAPTURE_START, message, &theKymera->lock);
}

void Kymera_StopVoiceCapture(void)
{
    kymeraTaskData *theKymera = KymeraGetTaskData();
    MessageSendConditionally((Task) &msg_handler, KYMERA_INTERNAL_VOICE_CAPTURE_STOP, NULL, &theKymera->lock);
}

void Kymera_StartWakeUpWordDetection(KymeraWakeUpWordDetected callback, const va_audio_wuw_detection_params_t *params)
{
    MESSAGE_MAKE(message, KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_START_T);
    kymeraTaskData *theKymera = KymeraGetTaskData();
    PanicFalse(callback && params);
    message->callback = callback;
    message->params = *params;
    MessageSendConditionally((Task) &msg_handler, KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_START, message, &theKymera->lock);
}

void Kymera_StopWakeUpWordDetection(void)
{
    kymeraTaskData *theKymera = KymeraGetTaskData();
    MessageSendConditionally((Task) &msg_handler, KYMERA_INTERNAL_WAKE_UP_WORD_DETECTION_STOP, NULL, &theKymera->lock);
}
