@startuml

    object OPR_LATENCY_BUFFER
    OPR_LATENCY_BUFFER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    object OPR_APTX_ADAPTIVE_TWS_PLUS_DECODER
    OPR_APTX_ADAPTIVE_TWS_PLUS_DECODER : id = EB_CAP_ID_APTX_ADAPTIVE_DECODE
    OPR_APTX_ADAPTIVE_TWS_PLUS_DECODER "IN(0)"<-- "OUT(0)" OPR_LATENCY_BUFFER
    object EPR_SINK_MEDIA #lightgreen
    OPR_LATENCY_BUFFER "IN(0)" <-- EPR_SINK_MEDIA
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT(0)" OPR_APTX_ADAPTIVE_TWS_PLUS_DECODER
@enduml
