@startuml

    object OPR_SCOFWD_RECV
    OPR_SCOFWD_RECV : id = EB_CAP_ID_ASYNC_WBS_DEC
    object OPR_SOURCE_SYNC
    OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
    object OPR_VOLUME_CONTROL
    OPR_VOLUME_CONTROL : id = EB_CAP_ID_VOL_CTRL_VOL
    object OPR_CVC_SEND
    OPR_CVC_SEND : id = CAP_ID_CVCHS1MIC_SEND_WB
    object OPR_MICFWD_SEND
    OPR_MICFWD_SEND : id = EB_CAP_ID_ASYNC_WBS_ENC
    object OPR_SWITCHED_PASSTHROUGH_CONSUMER
    OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_SCOFWD_RECV
    OPR_VOLUME_CONTROL "MAIN_IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
    OPR_MICFWD_SEND "IN(0)"<-- "OUT(0)" OPR_CVC_SEND
    OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_MICFWD_SEND
    object EPR_SCOFWD_RX_OTA #lightgreen
    OPR_SCOFWD_RECV "FORWARDED_AUDIO(0)" <-- EPR_SCOFWD_RX_OTA
    object EPR_VOLUME_AUX #lightgreen
    OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
    object EPR_CVC_SEND_REF_IN #lightgreen
    OPR_CVC_SEND "REFERENCE(0)" <-- EPR_CVC_SEND_REF_IN
    object EPR_CVC_SEND_IN1 #lightgreen
    OPR_CVC_SEND "IN1(1)" <-- EPR_CVC_SEND_IN1
    object EPR_MICFWD_TX_OTA #lightblue
    EPR_MICFWD_TX_OTA <-- "FORWARD(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
    object EPR_SCO_VOL_OUT #lightblue
    EPR_SCO_VOL_OUT <-- "OUT(0)" OPR_VOLUME_CONTROL
@enduml
