@startuml

    object OPR_SCO_RECEIVE
    OPR_SCO_RECEIVE : id = CAP_ID_WBS_DEC
    object OPR_SCO_SEND
    OPR_SCO_SEND : id = CAP_ID_WBS_ENC
    object OPR_CVC_RECEIVE
    OPR_CVC_RECEIVE : id = CAP_ID_CVC_RECEIVE_WB
    object OPR_SCOFWD_SPLITTER
    OPR_SCOFWD_SPLITTER : id = CAP_ID_SPLITTER
    object OPR_SCOFWD_BASIC_PASS
    OPR_SCOFWD_BASIC_PASS : id = CAP_ID_BASIC_PASS
    object OPR_SWITCHED_PASSTHROUGH_CONSUMER
    OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    object OPR_SCOFWD_SEND
    OPR_SCOFWD_SEND : id = EB_CAP_ID_ASYNC_WBS_ENC
    object OPR_CVC_SEND
    OPR_CVC_SEND : id = CAP_ID_CVCHS1MIC_SEND_WB
    object OPR_SOURCE_SYNC
    OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
    object OPR_VOLUME_CONTROL
    OPR_VOLUME_CONTROL : id = EB_CAP_ID_VOL_CTRL_VOL
    object OPR_MICFWD_RECV
    OPR_MICFWD_RECV : id = EB_CAP_ID_ASYNC_WBS_DEC
    object OPR_MICFWD_RECV_SPC
    OPR_MICFWD_RECV_SPC : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    object OPR_MICFWD_SPC_SWITCH
    OPR_MICFWD_SPC_SWITCH : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    OPR_CVC_RECEIVE "IN(0)"<-- "OUT(0)" OPR_SCO_RECEIVE
    OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_CVC_RECEIVE
    OPR_SCOFWD_SPLITTER "IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
    OPR_VOLUME_CONTROL "MAIN_IN(0)"<-- "OUT1(0)" OPR_SCOFWD_SPLITTER
    OPR_SCOFWD_BASIC_PASS "IN(0)"<-- "OUT2(1)" OPR_SCOFWD_SPLITTER
    OPR_SCOFWD_SEND "IN(0)"<-- "OUT(0)" OPR_SCOFWD_BASIC_PASS
    OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_SCOFWD_SEND
    OPR_MICFWD_SPC_SWITCH "LOCAL(0)"<-- "OUT(0)" OPR_CVC_SEND
    OPR_MICFWD_RECV "IN(0)"<-- "OUT(0)" OPR_MICFWD_RECV_SPC
    OPR_MICFWD_SPC_SWITCH "REMOTE(1)"<-- "OUT(0)" OPR_MICFWD_RECV
    OPR_SCO_SEND "IN(0)"<-- "CHOSEN(0)" OPR_MICFWD_SPC_SWITCH
    object EPR_SCO_FROM_AIR #lightgreen
    OPR_SCO_RECEIVE "SCO_IN(0)" <-- EPR_SCO_FROM_AIR
    object EPR_VOLUME_AUX #lightgreen
    OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
    object EPR_MICFWD_RX_OTA #lightgreen
    OPR_MICFWD_RECV_SPC "FORWARDED(0)" <-- EPR_MICFWD_RX_OTA
    object EPR_CVC_SEND_REF_IN #lightgreen
    OPR_CVC_SEND "REFERENCE(0)" <-- EPR_CVC_SEND_REF_IN
    object EPR_CVC_SEND_IN1 #lightgreen
    OPR_CVC_SEND "IN1(1)" <-- EPR_CVC_SEND_IN1
    object EPR_SCO_TO_AIR #lightblue
    EPR_SCO_TO_AIR <-- "SCO_OUT(0)" OPR_SCO_SEND
    object EPR_SCOFWD_TX_OTA #lightblue
    EPR_SCOFWD_TX_OTA <-- "FORWARD(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
    object EPR_SCO_VOL_OUT #lightblue
    EPR_SCO_VOL_OUT <-- "OUT(0)" OPR_VOLUME_CONTROL
@enduml
