@startuml

    object OPR_CVC_SEND
    OPR_CVC_SEND : id = EB_CAP_ID_CVC_VA_1MIC
    object EPR_VA_MIC_AEC_IN #lightgreen
    OPR_CVC_SEND "AEC_IN(0)" <-- EPR_VA_MIC_AEC_IN
    object EPR_VA_MIC_MIC1_IN #lightgreen
    OPR_CVC_SEND "MIC1_IN(1)" <-- EPR_VA_MIC_MIC1_IN
    object EPR_VA_MIC_ENCODE_OUT #lightblue
    EPR_VA_MIC_ENCODE_OUT <-- "OUT(0)" OPR_CVC_SEND
@enduml
