@startuml

    object OPR_LATENCY_BUFFER
    OPR_LATENCY_BUFFER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    object OPR_AAC_DECODER
    OPR_AAC_DECODER : id = EB_CAP_ID_AAC_DECODER
    object OPR_CONSUMER
    OPR_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    OPR_AAC_DECODER "IN(0)"<-- "OUT(0)" OPR_LATENCY_BUFFER
    OPR_CONSUMER "IN(0)"<-- "OUT_L(0)" OPR_AAC_DECODER
    object EPR_SINK_MEDIA #lightgreen
    OPR_LATENCY_BUFFER "IN(0)" <-- EPR_SINK_MEDIA
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT_R(1)" OPR_AAC_DECODER
@enduml
