@startuml

    object OPR_PROMPT_DECODER
    OPR_PROMPT_DECODER : id = CAP_ID_SBC_DECODER
    object OPR_TONE_PROMPT_BUFFER
    OPR_TONE_PROMPT_BUFFER : id = CAP_ID_BASIC_PASS
    OPR_TONE_PROMPT_BUFFER "IN(0)"<-- "OUT(0)" OPR_PROMPT_DECODER
    object EPR_PROMPT_IN #lightgreen
    OPR_PROMPT_DECODER "IN(0)" <-- EPR_PROMPT_IN
    object EPR_TONE_PROMPT_CHAIN_OUT #lightblue
    EPR_TONE_PROMPT_CHAIN_OUT <-- "OUT(0)" OPR_TONE_PROMPT_BUFFER
@enduml
