@startuml

    object OPR_RTP_DECODER
    OPR_RTP_DECODER : id = CAP_ID_RTP_DECODE
    object OPR_AAC_DECODER
    OPR_AAC_DECODER : id = EB_CAP_ID_AAC_DECODER
    object OPR_LEFT_RIGHT_MIXER
    OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
    OPR_AAC_DECODER "IN(0)"<-- "OUT(0)" OPR_RTP_DECODER
    OPR_LEFT_RIGHT_MIXER "IN_L(0)"<-- "OUT_0(0)" OPR_AAC_DECODER
    OPR_LEFT_RIGHT_MIXER "IN_R(1)"<-- "OUT_1(1)" OPR_AAC_DECODER
    object EPR_SINK_MEDIA #lightgreen
    OPR_RTP_DECODER "IN(0)" <-- EPR_SINK_MEDIA
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
@enduml
