@startuml

    object OPR_RTP_DECODER
    OPR_RTP_DECODER : id = CAP_ID_RTP_DECODE
    object OPR_APTX_DEMUX
    OPR_APTX_DEMUX : id = EB_CAP_ID_APTX_CLASSIC_DEMUX
    object OPR_SWITCHED_PASSTHROUGH_CONSUMER
    OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    object OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC
    OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC : id = CAP_ID_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC
    object OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC_SECONDARY
    OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC_SECONDARY : id = CAP_ID_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC
    object OPR_LEFT_RIGHT_MIXER
    OPR_LEFT_RIGHT_MIXER : id = CAP_ID_MIXER
    OPR_APTX_DEMUX "IN(0)"<-- "OUT(0)" OPR_RTP_DECODER
    OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN_0(0)"<-- "OUT_0(0)" OPR_APTX_DEMUX
    OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN_1(1)"<-- "OUT_1(1)" OPR_APTX_DEMUX
    OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC "IN(0)"<-- "OUT_0(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
    OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC_SECONDARY "IN(0)"<-- "OUT_1(1)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
    OPR_LEFT_RIGHT_MIXER "IN_0(0)"<-- "OUT(0)" OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC
    OPR_LEFT_RIGHT_MIXER "IN_1(1)"<-- "OUT(0)" OPR_APTX_CLASSIC_MONO_DECODER_NO_AUTOSYNC_SECONDARY
    object EPR_SINK_MEDIA #lightgreen
    OPR_RTP_DECODER "IN(0)" <-- EPR_SINK_MEDIA
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT(0)" OPR_LEFT_RIGHT_MIXER
@enduml
