@startuml

    object OPR_SWITCHED_PASSTHROUGH_CONSUMER
    OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = EB_CAP_ID_SWITCHED_PASSTHROUGH
    object OPR_APTX_ADAPTIVE_DECODER
    OPR_APTX_ADAPTIVE_DECODER : id = EB_CAP_ID_APTX_ADAPTIVE_DECODE
    OPR_APTX_ADAPTIVE_DECODER "IN(0)"<-- "OUT(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
    object EPR_SINK_MEDIA #lightgreen
    OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)" <-- EPR_SINK_MEDIA
    object EPR_SOURCE_DECODED_PCM #lightblue
    EPR_SOURCE_DECODED_PCM <-- "OUT(0)" OPR_APTX_ADAPTIVE_DECODER
@enduml
