@startuml

    object OPR_TONE_GEN
    OPR_TONE_GEN : id = CAP_ID_RINGTONE_GENERATOR
    object OPR_TONE_PROMPT_BUFFER
    OPR_TONE_PROMPT_BUFFER : id = CAP_ID_BASIC_PASS
    OPR_TONE_PROMPT_BUFFER "IN(0)"<-- "OUT(0)" OPR_TONE_GEN
    object EPR_TONE_PROMPT_CHAIN_OUT #lightblue
    EPR_TONE_PROMPT_CHAIN_OUT <-- "OUT(0)" OPR_TONE_PROMPT_BUFFER
@enduml
