@startuml

    object OPR_SCO_RECEIVE
    OPR_SCO_RECEIVE : id = CAP_ID_WBS_DEC
    object OPR_SCO_SEND
    OPR_SCO_SEND : id = CAP_ID_WBS_ENC
    object OPR_CVC_RECEIVE
    OPR_CVC_RECEIVE : id = CAP_ID_CVC_RECEIVE_WB
    object OPR_CVC_SEND
    OPR_CVC_SEND : id = CAP_ID_CVCHS2MIC_MONO_SEND_WB
    object OPR_SOURCE_SYNC
    OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
    object OPR_VOLUME_CONTROL
    OPR_VOLUME_CONTROL : id = EB_CAP_ID_VOL_CTRL_VOL
    OPR_CVC_RECEIVE "IN(0)"<-- "OUT(0)" OPR_SCO_RECEIVE
    OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_CVC_RECEIVE
    OPR_VOLUME_CONTROL "MAIN_IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
    OPR_SCO_SEND "IN(0)"<-- "OUT(0)" OPR_CVC_SEND
    object EPR_SCO_FROM_AIR #lightgreen
    OPR_SCO_RECEIVE "SCO_IN(0)" <-- EPR_SCO_FROM_AIR
    object EPR_VOLUME_AUX #lightgreen
    OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
    object EPR_CVC_SEND_REF_IN #lightgreen
    OPR_CVC_SEND "REFERENCE(0)" <-- EPR_CVC_SEND_REF_IN
    object EPR_CVC_SEND_IN1 #lightgreen
    OPR_CVC_SEND "IN1(1)" <-- EPR_CVC_SEND_IN1
    object EPR_CVC_SEND_IN2 #lightgreen
    OPR_CVC_SEND "IN2(2)" <-- EPR_CVC_SEND_IN2
    object EPR_SCO_TO_AIR #lightblue
    EPR_SCO_TO_AIR <-- "SCO_OUT(0)" OPR_SCO_SEND
    object EPR_SCO_VOL_OUT #lightblue
    EPR_SCO_VOL_OUT <-- "OUT(0)" OPR_VOLUME_CONTROL
@enduml
