@startuml

    object OPR_LATENCY_BUFFER
    OPR_LATENCY_BUFFER : id = CAP_ID_BASIC_PASS
    object OPR_SOURCE_SYNC
    OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
    object OPR_VOLUME_CONTROL
    OPR_VOLUME_CONTROL : id = EB_CAP_ID_VOL_CTRL_VOL
    OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_LATENCY_BUFFER
    OPR_VOLUME_CONTROL "MAIN_IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
    object EPR_SINK_MIXER_MAIN_IN #lightgreen
    OPR_LATENCY_BUFFER "IN(0)" <-- EPR_SINK_MIXER_MAIN_IN
    object EPR_VOLUME_AUX #lightgreen
    OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
    object EPR_SOURCE_MIXER_OUT #lightblue
    EPR_SOURCE_MIXER_OUT <-- "OUT(0)" OPR_VOLUME_CONTROL
@enduml
