@startuml

            skinparam roundcorner 20
            hide footbox
            participant "App Init" as init
            participant "Message Broker" as mb
            participant "<<UI_Provider>>\nTelephony" as tel #Thistle
            participant "TaskList" as tl
            participant "Message Loop" as ml
            participant "<<UI_Indicator>>\nLEDs" as led #LightBlue
            group Initialisation
                init -> mb: MessageBroker_Init(registrations[])
                ...
                led -> mb: MessageBroker_RegisterInterestInMsgGroups(led_task, led_grps, num_grps)
                mb  -> tel: message_group_register(led_task)
                note over mb
                    message_group_register is part of
                    message broker init registrations structure
                    (one structure per message group)
                end note
                ...
            end group
            ...
            tel -> tl: TaskList_SendMessage(led_task, "Telephony Connected")
            tl -> ml: MessageSend(led_task, "Telephony Connected")
            ml -> led: "Telephony Connected"
            note over led
                Flash LED to indicate connection
            end note
            @enduml
