/*!
\copyright  Copyright (c) 2020 Qualcomm Technologies International, Ltd.\n
            All Rights Reserved.\n
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\version    
\file       ${module}_db_if.h
\defgroup   ${module}_db
\brief      This implements an interface to allow common code to access application
            specific GATT database service constants.
*/

/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by dbgen_interface_generator.py
 */

#ifndef ${header_guard}_DB_IF_H__
#define ${header_guard}_DB_IF_H__

#include <csrtypes.h>

typedef enum {
${enum_list}
} gatt_attribute_t;

/*
 * NOTE:
 * This function is implemented in the application.
 */
extern uint16 getGattAttributeValue(gatt_attribute_t id, uint16 n);

/* Prototypes copied from gatt_handler_db.h */
uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

/* The gatt_handler_db.h defines, mapped to the above API */
/* But only if gatt_handler_db.h hasn't already been included */
${define_list}

#endif /* ${header_guard}_DB_IF_H__ */
