/*!
\copyright  Copyright (c) 2017 - 2020 Qualcomm Technologies International, Ltd.\n
            All Rights Reserved.\n
            Qualcomm Technologies International, Ltd. Confidential and Proprietary.
\file
\brief      Definitions of audio capability IDs
*/

#ifndef EARBUD_CAP_IDS_H
#define EARBUD_CAP_IDS_H

#if defined(__QCC3400_APP__) || defined(__QCC514X_APPS__)
#define DOWNLOAD_APTX_ADAPTIVE_DECODE
#define DOWNLOAD_SWITCHED_PASSTHROUGH
#ifdef ENABLE_AEC_LEAKTHROUGH
#define DOWNLOAD_AEC_REF
#endif
#elif defined(HAVE_STR_ROM_2_0_1)
#define DOWNLOAD_CVC_FBC
#elif defined(__QCC302X_APPS__) || defined(__QCC512X_APPS__)
#define DOWNLOAD_SWITCHED_PASSTHROUGH
#define DOWNLOAD_APTX_CLASSIC_DEMUX
#define DOWNLOAD_AEC_REF
#define DOWNLOAD_ASYNC_WBS_DEC
#define DOWNLOAD_ASYNC_WBS_ENC
#define DOWNLOAD_CVC_FBC
#endif

#ifdef DOWNLOAD_AAC_DECODER
#define EB_CAP_ID_AAC_DECODER CAP_ID_DOWNLOAD_AAC_DECODER
#else
#define EB_CAP_ID_AAC_DECODER CAP_ID_AAC_DECODER
#endif

#ifdef DOWNLOAD_SWITCHED_PASSTHROUGH
#define EB_CAP_ID_SWITCHED_PASSTHROUGH   CAP_ID_DOWNLOAD_SWITCHED_PASSTHROUGH_CONSUMER
#else
#define EB_CAP_ID_SWITCHED_PASSTHROUGH   CAP_ID_SWITCHED_PASSTHROUGH_CONSUMER
#endif

#ifdef DOWNLOAD_APTX_CLASSIC_DEMUX
#define EB_CAP_ID_APTX_CLASSIC_DEMUX     CAP_ID_DOWNLOAD_APTX_CLASSIC_DEMUX
#else
#define EB_CAP_ID_APTX_CLASSIC_DEMUX     CAP_ID_APTX_CLASSIC_DEMUX
#endif

#ifdef DOWNLOAD_AEC_REF
#define EB_CAP_ID_AEC_REF                CAP_ID_DOWNLOAD_AEC_REFERENCE
#else
#define EB_CAP_ID_AEC_REF                CAP_ID_AEC_REFERENCE
#endif

#ifdef DOWNLOAD_APTX_ADAPTIVE_DECODE
#define EB_CAP_ID_APTX_ADAPTIVE_DECODE   CAP_ID_DOWNLOAD_APTX_ADAPTIVE_DECODE
#else
#define EB_CAP_ID_APTX_ADAPTIVE_DECODE   CAP_ID_APTX_ADAPTIVE_DECODE
#endif

#ifdef DOWNLOAD_ASYNC_WBS_DEC
#define EB_CAP_ID_ASYNC_WBS_DEC          CAP_ID_DOWNLOAD_ASYNC_WBS_DEC
#else
#define EB_CAP_ID_ASYNC_WBS_DEC          CAP_ID_ASYNC_WBS_DEC
#endif

#ifdef DOWNLOAD_ASYNC_WBS_ENC
#define EB_CAP_ID_ASYNC_WBS_ENC          CAP_ID_DOWNLOAD_ASYNC_WBS_ENC
#else
#define EB_CAP_ID_ASYNC_WBS_ENC          CAP_ID_ASYNC_WBS_ENC
#endif

#ifdef DOWNLOAD_VOLUME_CONTROL
#define EB_CAP_ID_VOL_CTRL_VOL                CAP_ID_DOWNLOAD_VOL_CTRL_VOL
#else
#define EB_CAP_ID_VOL_CTRL_VOL                CAP_ID_VOL_CTRL_VOL
#endif

#ifdef DOWNLOAD_OPUS_CELT_ENCODE
#define EB_CAP_ID_OPUS_ENC          CAP_ID_DOWNLOAD_OPUS_CELT_ENCODE
#else
#define EB_CAP_ID_OPUS_ENC          CAP_ID_OPUS_CELT_ENCODE
#endif

#ifdef DOWNLOAD_VA_GRAPH_MANAGER
#define EB_CAP_ID_VA_GRAPH_MANAGER CAP_ID_DOWNLOAD_VA_GRAPH_MANAGER
#else
#define EB_CAP_ID_VA_GRAPH_MANAGER CAP_ID_VA_GRAPH_MANAGER
#endif

#if !(defined(__QCC3400_APP__) || defined(__QCC514X_APPS__))
#ifdef DOWNLOAD_CVC_FBC
#define EB_CAP_ID_CVC_FBC CAP_ID_DOWNLOAD_CVC_FBC
#else
#define EB_CAP_ID_CVC_FBC CAP_ID_CVC_FBC
#endif
#endif

#if defined(__QCC302X_APPS__) || defined(__QCC512X_APPS__)
#define EB_CAP_ID_CVC_VA_1MIC CAP_ID_CVCHS1MIC_SEND_WB
#else
#define EB_CAP_ID_CVC_VA_1MIC CAP_ID_CVCHS1MIC_SEND_WB
#endif

#endif // EARBUD_CAP_IDS_H
